# Generated by Django 4.2.1 on 2023-05-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='completed_as_form',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='completed_as_quiz',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_age',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='min_age',
            field=models.SmallIntegerField(),
        ),
    ]
