# Generated by Django 4.2.1 on 2023-05-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_quiz_max_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
