# Generated by Django 4.2.1 on 2023-05-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_quiz_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
