# Generated by Django 4.2.1 on 2023-05-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_quiz_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='average_score',
            field=models.IntegerField(default=0),
        ),
    ]
