# Generated by Django 4.2.1 on 2023-05-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_quiz_average_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('right_answer', models.CharField(max_length=50)),
                ('wrong_answer1', models.CharField(max_length=50)),
                ('wrong_answer2', models.CharField(max_length=50)),
                ('wrong_answer3', models.CharField(max_length=50)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.quiz')),
            ],
        ),
    ]
