# Generated by Django 4.2.1 on 2023-05-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
    ]
