# Generated by Django 4.2.1 on 2023-05-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_tag_alter_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='localized_uk_ua',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
