# Generated by Django 4.2.1 on 2023-05-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_tag_localized_uk_ua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='tags',
        ),
        migrations.AddField(
            model_name='quiz',
            name='tags',
            field=models.ManyToManyField(related_name='quizzes', to='home.tag'),
        ),
    ]
