# Generated by Django 4.2.1 on 2023-05-22 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_remove_quiz_tags_quiz_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_form', models.BooleanField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('right_answers', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers_amount',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='completed_as_form',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='completed_as_quiz',
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.BooleanField()),
                ('completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='home.completion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='home.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='home.quiz')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quiz_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='completion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='home.quiz'),
        ),
        migrations.AddField(
            model_name='completion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='completions', to=settings.AUTH_USER_MODEL),
        ),
    ]
