# Generated by Django 4.2.1 on 2023-05-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_quiz_searchable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='searchable',
        ),
    ]
