# Generated by Django 4.2.1 on 2023-05-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_quiz_searchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='searchable',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
