# Generated by Django 4.2.1 on 2023-05-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_quiz_searchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='token',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
