# Generated by Django 4.2.1 on 2025-05-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_completion_score_alter_completion_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completion',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
